spring:
  config:
    import:
      - config/system/application-system.yml
      - config/system/application-system-prod.yml
      - config/jdbc/application-jdbc-prod.yml
      - config/third-party/application-third-party-prod.yml