# Third Party Local Settings
spring:
  config:
    import:
      - application-third-party.yml

app:
  ctrs:
    url:
      host: http://localhost:8080

  vms:
    url:
      host: https://www.klid.vms.com:7443

  ctss:
    url:
      host: https://www.klid.vms.com:7443
