# Third Party Stage Settings
spring:
  config:
    import:
      - application-third-party.yml

app:
  ctrs:
    url:
      host: https://10.46.126.211

  vms:
    url:
      host: http://10.46.126.222:8445

  ctss:
    url:
      host: http://10.46.126.222:8445
